AppBundle\Entity\Card:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CardRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
        sign:
            type: string
            length: 255
    lifecycleCallbacks: {  }
