AppBundle\Entity\Deck:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DeckRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
    lifecycleCallbacks: {  }
